project_id = "vipltojtcrqatwvzobro"

[functions.create-pix-payment]
verify_jwt = false

[functions.create-asaas-payment]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.pagarme-webhook]
verify_jwt = false

[functions.send-access-link]
verify_jwt = false

[functions.check-order-status]
verify_jwt = false